import { Link } from 'react-router-dom';
import { useAuth } from '../../auth/useAuth';
import { formatTripDate, operationsApi } from '../../operations/operationsApi';
import { useOperations } from '../../operations/useOperations';

export default function OperationsPortal({kind}:{kind:'owner'|'crew'}) {
 const {logout}=useAuth(); const {boats,trips,loading,error,reload,token}=useOperations();
 const update=async(id:string,status:string)=>{if(!token)return;await operationsApi.status(token,id,status);await reload();};
 return <div className="min-h-screen bg-[#f8f9fb] font-[Poppins] text-[#14223d]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link to={`/${kind}`} className="text-lg font-bold">WWMS · {kind==='owner'?'Boat Owner':'Boat Crew'}</Link><button onClick={logout} className="rounded bg-[#14223d] px-4 py-2 text-sm text-white">Log Out</button></div></header><main className="mx-auto max-w-7xl px-6 py-10"><h1 className="text-3xl font-semibold">{kind==='owner'?'My Fleet':'My Assignments'}</h1><p className="mt-2 text-sm text-slate-500">Shared live data from the WWMS backend.</p>{loading&&<p className="mt-8">Loading…</p>}{error&&<p className="mt-8 text-red-600">{error}</p>}<section className="mt-8 grid gap-4 md:grid-cols-2">{boats.map(b=><article key={b.id} className="rounded-xl bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">{b.name}</h2><span className="text-sm text-emerald-600">{b.approval}</span></div><p className="mt-2 text-sm text-slate-500">{b.registrationNumber} · Capacity {b.maximumCapacity}</p></article>)}</section><h2 className="mt-10 text-2xl font-semibold">Trips</h2><section className="mt-4 grid gap-4">{trips.map(t=><article key={t.id} className="rounded-xl bg-white p-6 shadow-sm md:flex md:items-center md:justify-between"><div><strong>{t.vesselName}</strong><p className="mt-1 text-sm text-slate-500">{t.route} · {formatTripDate(t.scheduledDepartureUtc)}</p><p className="mt-1 text-xs">Shore: {t.shoreApproval} · Status: {t.status}</p></div><div className="mt-4 flex gap-2 md:mt-0"><button onClick={()=>void update(t.id,'Ongoing')} className="rounded border px-3 py-2 text-sm">Start</button><button onClick={()=>void update(t.id,'Completed')} className="rounded bg-[#14223d] px-3 py-2 text-sm text-white">Complete</button></div></article>)}</section></main></div>;
}
