import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useAuth } from "../../auth/useAuth";
import { operationsApi } from "../../operations/operationsApi";
import { useAdminRecords } from "./AdminRecordsContext";
import ApprovalControls from "./components/ApprovalControls";
import EditRecordModal from "./components/EditRecordModal";
import TripHistory from "./components/TripHistory";

export default function BoatDetailsPage(){
 const{id,fleetId,boatId}=useParams();const nav=useNavigate();const{session}=useAuth();const records=useAdminRecords();
 const boat=records.boats.find(b=>b.id===Number(boatId??fleetId??id));const[editing,setEditing]=useState(false);
 if(!boat)return <main className="p-10 text-center">Boat not found.</main>;
 const owner=records.owners.find(o=>o.id===boat.ownerId);const ownerCrew=records.crew.filter(c=>c.ownerId===boat.ownerId);
 const prefix=session?.roles.includes("Wildlife")?"/wildlife":"/admin";
 const remove=()=>{if(confirm(`Delete ${boat.name}? Crew members will become unassigned. This cannot be undone.`)){records.deleteBoat(boat.id);nav(`${prefix}/boats`)}};
 const openDocument=async(documentId:string,download=false)=>{if(!session||!boat.apiId)return;const url=await operationsApi.downloadBoatDocument(session.accessToken,boat.apiId,documentId);if(download){const link=document.createElement("a");link.href=url;link.download=boat.documents?.find(item=>item.id===documentId)?.fileName??"certificate";link.click()}else window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60000)};
 return <main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-wrap justify-between gap-3"><button onClick={()=>nav(-1)} className="text-sm font-semibold text-indigo-700">← Back to boats</button><div className="flex gap-3"><button onClick={()=>setEditing(true)} className="rounded-lg border border-slate-300 px-5 py-2 text-sm font-semibold">Edit</button><button onClick={remove} className="rounded-lg bg-red-600 px-5 py-2 text-sm font-semibold text-white">Delete</button></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-[360px_1fr]"><aside className="space-y-6"><section className="overflow-hidden rounded-2xl bg-white shadow-sm">{boat.imageUrl?<img src={boat.imageUrl} alt={`${boat.name} uploaded by owner`} className="h-48 w-full object-cover"/>:<div className="flex h-48 items-center justify-center bg-gradient-to-br from-blue-200 to-cyan-100 text-6xl">⚓</div>}<div className="p-6"><h1 className="text-2xl font-semibold">{boat.name}</h1><p className="mt-1 text-sm text-slate-500">{boat.registrationNumber}</p><dl className="mt-6 grid grid-cols-2 gap-4 text-sm">{[["Registered",boat.registrationDate],["Hull no.",boat.hullNumber],["Capacity",boat.capacity],["Length",boat.length],["Width",boat.width]].map(([label,value])=><div key={label}><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></div></section><ApprovalControls key={`${boat.approval}-${boat.declineReason}`} initialStatus={boat.approval} initialReason={boat.declineReason} onChange={(status,reason)=>records.setBoatApproval(boat.id,status,reason)}/></aside>
 <div className="space-y-6"><Card title="Owner">{owner&&<Link to={`${prefix}/owners/${owner.id}`} className="mt-4 flex justify-between rounded-xl border p-4"><span className="font-semibold">{owner.name}</span><span className="text-indigo-700">View →</span></Link>}</Card><Card title={`Owner's crew (${ownerCrew.length})`}><div className="mt-4 grid gap-3 sm:grid-cols-2">{ownerCrew.map(member=><Link key={member.id} to={`${prefix}/crew/${member.id}`} className="rounded-xl border p-4"><p className="font-semibold">{member.name}</p><p className="text-xs text-slate-500">{member.role}{member.boatId===boat.id?" · Assigned to this boat":""}</p></Link>)}</div>{ownerCrew.length===0&&<p className="mt-4 text-sm text-slate-500">No crew members have been added by this owner.</p>}</Card>
 <Card title="Certifications"><div className="mt-4 grid gap-3 sm:grid-cols-2">{boat.documents?.map(item=><article key={item.id} className="rounded-lg bg-slate-50 p-4"><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 truncate text-xs text-slate-500">{item.fileName}</p><div className="mt-3 flex gap-3"><button onClick={()=>void openDocument(item.id)} className="text-xs font-semibold text-indigo-700">View</button><button onClick={()=>void openDocument(item.id,true)} className="text-xs font-semibold text-indigo-700">Download</button></div></article>)}</div>{!boat.documents?.length&&<p className="mt-4 text-sm text-slate-500">No certificates uploaded.</p>}</Card><TripHistory tripIds={boat.tripIds}/></div></div>
 {editing&&<EditRecordModal title="boat" fields={[{key:"name",label:"Boat name"},{key:"registrationNumber",label:"Registration number"},{key:"registrationDate",label:"Registration date",type:"date"},{key:"hullNumber",label:"Hull number"},{key:"capacity",label:"Maximum capacity",type:"number"},{key:"length",label:"Length"},{key:"width",label:"Width"},{key:"ownerId",label:"Owner",type:"select",options:records.owners.map(o=>({label:o.name,value:String(o.id)}))}]} initial={boat} onClose={()=>setEditing(false)} onSave={values=>{records.updateBoat(boat.id,{...values,capacity:Number(values.capacity),ownerId:Number(values.ownerId)});setEditing(false)}}/>}</main>;
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">{title}</h2>{children}</section>}
