import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../auth/useAuth';
import { wildlifeApi, watchAttendance, type Attendance, type MonitoringRecord, type WildlifeTrip } from './shoreWildlifeApi';

const formatDate=(v:string)=>new Intl.DateTimeFormat('en-LK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
const Shell=({title,sub,children}:{title:string;sub:string;children:React.ReactNode})=><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><h1 className="text-3xl font-semibold text-[#14223d]">{title}</h1><p className="mt-1 text-sm text-slate-500">{sub}</p><div className="mt-7">{children}</div></main>;
const Badge=({value}:{value:string})=>{const c=value==='Approved'?'bg-emerald-50 text-emerald-700':value==='Rejected'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700';return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${c}`}>{value}</span>};

export function WildlifeTrips(){
 const{session}=useAuth();const nav=useNavigate();const[items,setItems]=useState<WildlifeTrip[]>([]);const[query,setQuery]=useState('');const[sort,setSort]=useState('newest');const[error,setError]=useState('');
 useEffect(()=>{if(session)wildlifeApi.trips(session.accessToken).then(setItems).catch(e=>setError(e instanceof Error?e.message:String(e)))},[session]);
 const visible=useMemo(()=>items.filter(x=>[x.boatName,x.registrationNumber,x.ownerName,x.route,x.status,x.wildlifeShoreApproval].some(v=>v.toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>sort==='oldest'?+new Date(a.scheduledDepartureUtc)-+new Date(b.scheduledDepartureUtc):sort==='name'?a.boatName.localeCompare(b.boatName):sort==='approval'?a.wildlifeShoreApproval.localeCompare(b.wildlifeShoreApproval):+new Date(b.scheduledDepartureUtc)-+new Date(a.scheduledDepartureUtc)),[items,query,sort]);
 return <Shell title="Trips" sub="Monitor attendance and complete Wildlife Shore approval"><section className="overflow-hidden rounded-xl bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vessel, owner, registration or route" className="min-w-0 flex-1 rounded-lg border border-slate-200 px-4 py-2.5 text-sm outline-none focus:border-indigo-400"/><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Vessel A–Z</option><option value="approval">Approval status</option></select></div>{error&&<p className="p-5 text-red-600">{error}</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50/70 text-xs text-slate-500"><tr><th className="px-6 py-4">Vessel</th><th className="px-5 py-4">Owner</th><th className="px-5 py-4">Scheduled</th><th className="px-5 py-4">SLCG</th><th className="px-5 py-4">Wildlife Shore</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y">{visible.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-6 py-5"><b>{x.boatName}</b><p className="text-xs text-slate-400">{x.registrationNumber}</p></td><td className="px-5 py-5">{x.ownerName}</td><td className="px-5 py-5">{formatDate(x.scheduledDepartureUtc)}</td><td className="px-5 py-5"><Badge value={x.shoreApproval}/></td><td className="px-5 py-5"><Badge value={x.wildlifeShoreApproval}/></td><td className="px-6 py-5 text-right"><button onClick={()=>nav(`/shore-wildlife/trips/${x.id}`)} className="rounded-full border border-indigo-200 px-3 py-1 text-xs font-medium text-indigo-700">Review</button></td></tr>)}</tbody></table></div>{visible.length===0&&<p className="p-12 text-center text-sm text-slate-400">No trips match your search.</p>}</section></Shell>;
}

function Breakdown({a}:{a:Attendance}){return <section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between"><div><h2 className="text-xl font-semibold">Passenger Attendance</h2><p className="mt-1 text-sm font-semibold text-emerald-600">● Live Attendance</p></div><p className="text-xs text-slate-500">Last updated: {formatDate(a.lastUpdatedUtc)}</p></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Group name="LOCAL" x={a.local}/><Group name="FOREIGN" x={a.foreign}/></div><div className="mt-5 rounded-xl bg-[#14223d] p-5 text-white"><p className="text-xs uppercase">Total present</p><p className="text-4xl font-bold">{a.totalPresent}</p></div></section>}
function Group({name,x}:{name:string;x:Attendance['local']}){return <div className="rounded-xl border p-5"><h3 className="font-semibold">{name}</h3>{[['Adult',x.adult],['Child',x.child],['Small (Under 6 Y)',x.small]].map(([l,v])=><div key={String(l)} className="mt-3 flex justify-between text-sm"><span>{l}</span><b>{v}</b></div>)}<div className="mt-4 flex justify-between border-t pt-3 font-semibold"><span>Total</span><b>{x.total}</b></div></div>}

export function WildlifeTripDetails(){
 const{id=''}=useParams();const{session}=useAuth();const nav=useNavigate();const[a,setA]=useState<Attendance>();const[record,setRecord]=useState<MonitoringRecord>();const[form,setForm]=useState({ticketNumber:'',tidNumber:'',monitoringOfficer:'',supervisor:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(()=>{if(session)wildlifeApi.attendance(session.accessToken,id).then(setA).catch(e=>setError(e.message))},[session,id]);useEffect(()=>{load();if(session)return watchAttendance(session.accessToken,load)},[load,session]);
 useEffect(()=>{if(!session)return;wildlifeApi.records(session.accessToken).then(rows=>{const existing=rows.find(x=>x.tripId===id);if(existing){setRecord(existing);setForm({ticketNumber:existing.ticketNumber,tidNumber:existing.tidNumber,monitoringOfficer:existing.monitoringOfficer,supervisor:existing.supervisor})}}).catch(()=>undefined)},[session,id]);
 const request=async()=>{if(!session)return;setBusy(true);setError('');try{let r=record;if(!r)r=await wildlifeApi.create(session.accessToken,{tripId:id,...form});setRecord(await wildlifeApi.requestSignature(session.accessToken,r.id,form))}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}};
 const approve=async(value:'Approved'|'Rejected')=>{if(!session)return;setBusy(true);setError('');try{await wildlifeApi.approve(session.accessToken,id,value);load()}catch(e){setError(e instanceof Error?e.message:'Approval failed')}finally{setBusy(false)}};
 if(!a)return <Shell title="Trip monitoring" sub="Loading latest attendance…"><p>{error}</p></Shell>;
 const boatApproval=a.certificationApproval==='Approved'||a.boatWildlifeApproval==='Approved'?'Approved':a.certificationApproval==='Rejected'&&a.boatWildlifeApproval==='Rejected'?'Rejected':'Pending';
 const signaturesComplete=Boolean(record?.monitoringOfficerSignature&&record?.supervisorSignature&&record?.harbourOfficerSignature&&record?.harbourOfficerName);
 return <Shell title={a.boatName} sub={`${a.registrationNumber} · ${formatDate(a.scheduledDepartureUtc)}`}><button onClick={()=>nav('/shore-wildlife')} className="mb-5 text-sm font-semibold text-indigo-700">← Trips</button><div className="grid gap-6 lg:grid-cols-[1fr_.9fr]"><div className="space-y-6"><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="font-semibold">Trip Information</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info l="Trip reference" v={a.tripId}/><Info l="Boat operator" v={a.ownerName}/><Info l="Route" v={a.route}/><Info l="Status" v={a.tripStatus}/></dl><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><div>Boat approval<br/><Badge value={boatApproval}/></div><div>SLCG Shore<br/><Badge value={a.shoreApproval}/></div><div>Wildlife Shore<br/><Badge value={a.wildlifeShoreApproval}/></div></div></section><Breakdown a={a}/></div><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Monitoring Information</h2><div className="mt-5 grid gap-4">{(['ticketNumber','tidNumber','monitoringOfficer','supervisor'] as const).map(k=><label key={k} className="text-sm font-medium">{{ticketNumber:'Ticket Number',tidNumber:'TID Number',monitoringOfficer:'Monitoring Officer',supervisor:'Supervisor'}[k]}<input disabled={record?.status==='Completed'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} maxLength={k==='ticketNumber'||k==='tidNumber'?80:160} className="mt-1 block w-full rounded-lg border px-3 py-2.5"/></label>)}</div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{record&&((record.status==='PendingHarbourSignature')||(record.status==='Completed'&&!signaturesComplete))?<SignatureSection record={record} token={session!.accessToken} done={r=>{setRecord(r);setError('')}}/>:<button disabled={busy||record?.status==='Completed'||Object.values(form).some(v=>!v.trim())} onClick={request} className="mt-6 w-full rounded-lg bg-[#14223d] px-4 py-3 font-semibold text-white disabled:opacity-40">{busy?'Saving…':signaturesComplete?'All signatures completed':'Request Signatures'}</button>}{record?.status==='Completed'&&signaturesComplete&&<div className="mt-7 border-t pt-5"><h3 className="font-semibold">Wildlife Shore Approval</h3><p className="mt-1 text-xs text-slate-500">All monitoring fields and signatures are complete.</p><div className="mt-4 flex gap-3"><button disabled={busy} onClick={()=>approve('Rejected')} className="flex-1 rounded-lg border border-red-300 py-2.5 font-semibold text-red-700">Reject</button><button disabled={busy||a.wildlifeShoreApproval==='Approved'} onClick={()=>approve('Approved')} className="flex-1 rounded-lg bg-emerald-600 py-2.5 font-semibold text-white disabled:opacity-50">Approve Trip</button></div></div>}</section></div></Shell>;
}

function SignaturePad({label,onChange}:{label:string;onChange:(v:string)=>void}){const ref=useRef<HTMLCanvasElement>(null);const[drawing,setDrawing]=useState(false);const[hasInk,setHasInk]=useState(false);const pos=(e:PointerEvent<HTMLCanvasElement>)=>{const c=ref.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};const start=(e:PointerEvent<HTMLCanvasElement>)=>{const c=ref.current!,p=pos(e),x=c.getContext('2d')!;x.beginPath();x.moveTo(p.x,p.y);setDrawing(true);e.currentTarget.setPointerCapture(e.pointerId)};const move=(e:PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const c=ref.current!,p=pos(e),x=c.getContext('2d')!;x.lineWidth=3;x.lineCap='round';x.strokeStyle='#14223d';x.lineTo(p.x,p.y);x.stroke();setHasInk(true);onChange(c.toDataURL('image/png'))};const clear=()=>{ref.current?.getContext('2d')?.clearRect(0,0,700,180);setHasInk(false);onChange('')};return <div><div className="mb-2 flex justify-between"><label className="text-sm font-medium">{label}</label><button onClick={clear} className="text-xs text-indigo-700">Clear</button></div><canvas ref={ref} width="700" height="180" onPointerDown={start} onPointerMove={move} onPointerUp={()=>setDrawing(false)} onPointerCancel={()=>setDrawing(false)} className={`h-32 w-full touch-none rounded-lg border bg-white ${hasInk?'border-emerald-400':'border-slate-300'}`}/></div>}
function SignatureSection({record,token,done}:{record:MonitoringRecord;token:string;done:(r:MonitoringRecord)=>void}){const[harbour,setHarbour]=useState('');const[sigs,setSigs]=useState({monitoringOfficerSignature:'',supervisorSignature:'',harbourOfficerSignature:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{done(await wildlifeApi.sign(token,record.id,{harbourOfficerName:harbour,...sigs}))}catch(e){setError(e instanceof Error?e.message:'Signing failed')}finally{setBusy(false)}};return <div className="mt-7 space-y-5 border-t pt-6"><h3 className="font-semibold">Required Signatures</h3><SignaturePad label={`Monitoring Officer — ${record.monitoringOfficer}`} onChange={v=>setSigs(x=>({...x,monitoringOfficerSignature:v}))}/><SignaturePad label={`Supervisor — ${record.supervisor}`} onChange={v=>setSigs(x=>({...x,supervisorSignature:v}))}/><input value={harbour} onChange={e=>setHarbour(e.target.value)} placeholder="Harbour Officer name" maxLength={160} className="w-full rounded-lg border px-3 py-2.5"/><SignaturePad label="Harbour Officer" onChange={v=>setSigs(x=>({...x,harbourOfficerSignature:v}))}/>{error&&<p className="text-sm text-red-600">{error}</p>}<button disabled={busy||!harbour.trim()||Object.values(sigs).some(v=>!v)} onClick={submit} className="w-full rounded-lg bg-emerald-600 py-3 font-semibold text-white disabled:opacity-40">{busy?'Saving signatures…':'Confirm All Signatures'}</button></div>}

export function WildlifeRecords(){const{session}=useAuth();const[rows,setRows]=useState<MonitoringRecord[]>([]);const[open,setOpen]=useState<string>();useEffect(()=>{if(session)wildlifeApi.records(session.accessToken).then(setRows)},[session]);const download=(r:MonitoringRecord)=>{const safe={...r,monitoringOfficerSignature:'[signature stored]',supervisorSignature:'[signature stored]',harbourOfficerSignature:'[signature stored]'};const blob=new Blob([JSON.stringify(safe,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`wildlife-monitoring-${r.ticketNumber}.json`;a.click();URL.revokeObjectURL(url)};return <Shell title="Monitoring Records" sub="View and download finalized attendance snapshots"><div className="space-y-3">{rows.map(r=><section key={r.id} className="rounded-xl bg-white shadow-sm"><button onClick={()=>setOpen(open===r.id?undefined:r.id)} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 p-5 text-left"><div><b>{r.ticketNumber}</b><p className="text-xs text-slate-500">Trip {r.tripId.slice(0,8)} · {r.totalPresent} present · {formatDate(r.createdAtUtc)}</p></div><span className="text-indigo-700">{open===r.id?'Hide':'View'} ▾</span></button>{open===r.id&&<div className="border-t p-5"><dl className="grid gap-4 text-sm sm:grid-cols-3"><Info l="TID" v={r.tidNumber}/><Info l="Monitoring Officer" v={r.monitoringOfficer}/><Info l="Supervisor" v={r.supervisor}/><Info l="Harbour Officer" v={r.harbourOfficerName??'—'}/><Info l="Local snapshot" v={String(r.local.total)}/><Info l="Foreign snapshot" v={String(r.foreign.total)}/></dl><div className="mt-5 grid gap-3 sm:grid-cols-3">{[[r.monitoringOfficerSignature,'Monitoring Officer'],[r.supervisorSignature,'Supervisor'],[r.harbourOfficerSignature,'Harbour Officer']].map(([src,label])=><div key={label} className="rounded-lg border p-3"><p className="text-xs font-medium">{label}</p>{src?<img src={src} alt={`${label} signature`} className="mt-2 h-20 w-full object-contain"/>:<p className="mt-2 text-xs text-slate-400">Not signed</p>}</div>)}</div><button onClick={()=>download(r)} className="mt-5 rounded-lg bg-[#14223d] px-5 py-2.5 text-sm font-semibold text-white">Download Record</button></div>}</section>)}</div></Shell>}
function Info({l,v}:{l:string;v:string}){return <div><dt className="text-xs uppercase text-slate-400">{l}</dt><dd className="mt-1 break-words font-semibold">{v}</dd></div>}
