import { HubConnectionBuilder } from '@microsoft/signalr';
const BASE=(import.meta.env.VITE_API_BASE_URL??'').replace(/\/$/,'');
export interface Count{adult:number;child:number;small:number;total:number}
export interface WildlifeTrip{id:string;boatName:string;registrationNumber:string;ownerName:string;scheduledDepartureUtc:string;route:string;status:string;registeredPassengers:number;shoreApproval:string;wildlifeShoreApproval:string;certificationApproval:string;boatWildlifeApproval:string}
export interface Attendance{tripId:string;boatName:string;registrationNumber:string;ownerName:string;scheduledDepartureUtc:string;route:string;tripStatus:string;shoreApproval:string;wildlifeShoreApproval:string;certificationApproval:string;boatWildlifeApproval:string;local:Count;foreign:Count;totalPresent:number;lastUpdatedUtc:string}
export interface MonitoringRecord{id:string;tripId:string;ticketNumber:string;tidNumber:string;monitoringOfficer:string;supervisor:string;status:string;local:Count;foreign:Count;totalPresent:number;harbourOfficerName?:string;signedAtUtc?:string;createdAtUtc:string;completedAtUtc?:string;monitoringOfficerSignature?:string;supervisorSignature?:string;harbourOfficerSignature?:string}
async function req<T>(token:string,path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${BASE}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init?.headers}});if(!r.ok){const p=await r.json().catch(()=>null) as {message?:string;title?:string}|null;throw new Error(p?.message??p?.title??`Request failed (${r.status})`)}return r.json() as Promise<T>}
export const wildlifeApi={trips:(t:string)=>req<WildlifeTrip[]>(t,'/api/shore-wildlife/trips'),attendance:(t:string,id:string)=>req<Attendance>(t,`/api/shore-wildlife/trips/${id}/attendance`),records:(t:string)=>req<MonitoringRecord[]>(t,'/api/shore-wildlife/records'),record:(t:string,id:string)=>req<MonitoringRecord>(t,`/api/shore-wildlife/records/${id}`),create:(t:string,x:{tripId:string;ticketNumber:string;tidNumber:string;monitoringOfficer:string;supervisor:string})=>req<MonitoringRecord>(t,'/api/shore-wildlife/records',{method:'POST',body:JSON.stringify(x)}),requestSignature:(t:string,id:string,x:{ticketNumber:string;tidNumber:string;monitoringOfficer:string;supervisor:string})=>req<MonitoringRecord>(t,`/api/shore-wildlife/records/${id}`,{method:'PUT',body:JSON.stringify(x)}),sign:(t:string,id:string,x:{harbourOfficerName:string;monitoringOfficerSignature:string;supervisorSignature:string;harbourOfficerSignature:string})=>req<MonitoringRecord>(t,`/api/shore-wildlife/records/${id}/sign`,{method:'POST',body:JSON.stringify(x)}),approve:(t:string,tripId:string,approval:'Approved'|'Rejected',notes?:string)=>req<WildlifeTrip>(t,`/api/shore-wildlife/trips/${tripId}/approval`,{method:'PATCH',body:JSON.stringify({approval,notes})})};
export function watchAttendance(token:string,onChange:()=>void){const c=new HubConnectionBuilder().withUrl(`${BASE}/hubs/operations`,{accessTokenFactory:()=>token}).withAutomaticReconnect().build();c.on('operationsChanged',(e:{entity?:string})=>{if(e?.entity?.startsWith('passengerAttendance'))onChange()});void c.start();return()=>{void c.stop()}}
