import { useEffect, useRef, useState } from "react";
import { Camera, Search, X } from "lucide-react";
import { shoreAttendanceApi, type AttendanceManifest, type AttendanceStatus, type PassengerGroup, type PassengerGroupSearch } from "./shoreAttendanceApi";

export default function PassengerAttendancePanel({token,tripId}:{token:string;tripId:string}){
 const[manifest,setManifest]=useState<AttendanceManifest>();const[group,setGroup]=useState<PassengerGroup>();const[statuses,setStatuses]=useState<Record<string,AttendanceStatus>>({});const[query,setQuery]=useState("");const[results,setResults]=useState<PassengerGroupSearch[]>([]);const[scanner,setScanner]=useState(false);const[review,setReview]=useState(false);const[finalize,setFinalize]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=async()=>{try{setManifest(await shoreAttendanceApi.manifest(token,tripId));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load attendance.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[token,tripId]);
 useEffect(()=>{const term=query.trim();if(term.length<2){setResults([]);return}let active=true;const timer=window.setTimeout(()=>void shoreAttendanceApi.search(token,tripId,term).then(items=>{if(active)setResults(items)}).catch(()=>{if(active)setResults([])}),300);return()=>{active=false;window.clearTimeout(timer)}},[query,token,tripId]);
 const openGroup=(value:PassengerGroup)=>{setGroup(value);setStatuses(Object.fromEntries(value.members.map(member=>[member.passengerId,member.status])));setResults([]);setQuery("");setError("")};
 const scan=async(value:string)=>{try{setScanner(false);openGroup(await shoreAttendanceApi.scan(token,tripId,value))}catch(e){setError(e instanceof Error?e.message:"Unable to validate passenger QR.")}};
 const openSearch=async(id:string)=>{try{openGroup(await shoreAttendanceApi.group(token,tripId,id))}catch(e){setError(e instanceof Error?e.message:"Unable to open passenger group.")}};
 const save=async()=>{if(!group)return;try{setLoading(true);const updated=await shoreAttendanceApi.saveGroup(token,tripId,group.primaryPassengerId,group.members.map(member=>({passengerId:member.passengerId,status:statuses[member.passengerId]??'NotChecked'})));openGroup(updated);setReview(false);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save attendance.")}finally{setLoading(false)}};
 const finalizeManifest=async()=>{if(!manifest)return;try{setLoading(true);setManifest(await shoreAttendanceApi.finalize(token,tripId,manifest.summary.notChecked>0));setFinalize(false)}catch(e){setError(e instanceof Error?e.message:"Unable to finalize attendance.")}finally{setLoading(false)}};
 if(loading&&!manifest)return <section className="rounded-xl bg-white p-6 shadow-sm">Loading passenger attendance...</section>;
 const summary=manifest?.summary??{present:0,notPresent:0,notChecked:0,total:0};const selected=Object.values(statuses);const groupPresent=selected.filter(x=>x==='Present').length;const groupAbsent=selected.filter(x=>x==='NotPresent').length;const groupUnchecked=selected.filter(x=>x==='NotChecked').length;const percent=summary.total?Math.round(summary.present/summary.total*100):0;
 return <section className="space-y-5">
  {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
  <section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-[#14223d]">Passenger Attendance</h2><p className="mt-1 text-sm font-semibold text-indigo-700">{summary.present} of {summary.total} passengers are Present</p></div>{manifest?.finalizedAtUtc&&<span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">Finalized by {manifest.finalizedBy}</span>}</div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-500" style={{width:`${percent}%`}}/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Present Today" value={summary.present} color="text-emerald-600"/><Metric label="Not Present" value={summary.notPresent} color="text-red-600"/><Metric label="Not Yet Checked" value={summary.notChecked} color="text-slate-500"/><Metric label="Total Registered" value={summary.total} color="text-[#14223d]"/></div></section>
  <section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#14223d]">Passenger Check-In</h2><p className="mt-1 text-xs text-slate-500">Scan the primary passenger’s personal QR to retrieve their registered group.</p></div><button type="button" disabled={Boolean(manifest?.finalizedAtUtc)} onClick={()=>setScanner(true)} className="flex items-center gap-2 rounded-lg bg-[#14223d] px-4 py-3 text-sm font-semibold text-white disabled:opacity-40"><Camera size={18}/>Scan Passenger QR</button></div><div className="relative mt-5"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search passenger name, reference, or registration ID" className="h-11 w-full rounded-lg border border-slate-200 pl-10 pr-4 text-sm outline-none focus:border-indigo-400"/></div>{results.length>0&&<div className="mt-2 overflow-hidden rounded-lg border">{results.map(item=><button type="button" key={item.primaryPassengerId} onClick={()=>void openSearch(item.primaryPassengerId)} className="flex w-full justify-between border-t p-3 text-left text-xs first:border-0 hover:bg-slate-50"><span><b className="block text-sm">{item.primaryPassengerName}</b>{item.passengerReference}</span><span>{item.memberCount} passengers · {item.alreadyProcessed?'Checked':'Not checked'}</span></button>)}</div>}</section>
  {group&&<section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#14223d]">{group.primaryPassengerName}’s Group</h2><p className="mt-1 text-xs text-slate-500">Primary reference: {group.primaryPassengerReference} · Trip {group.tripId}</p>{group.alreadyProcessed&&<p className="mt-2 text-xs font-semibold text-indigo-700">This passenger group has already been checked. Existing statuses are shown below.</p>}</div><button onClick={()=>setGroup(undefined)} className="text-slate-400"><X/></button></div><div className="mt-5 space-y-3">{group.members.map(member=><article key={member.passengerId} className="grid gap-3 rounded-lg border p-4 md:grid-cols-[1fr_auto]"><div><p className="font-semibold text-[#14223d]">{member.name}</p><p className="mt-1 text-xs text-slate-500">{member.relationship} · {member.passengerReference} · {member.phoneNumber}</p><StatusBadge status={statuses[member.passengerId]??member.status}/></div><div className="flex flex-wrap items-center gap-2"><StatusButton label="Present" active={statuses[member.passengerId]==='Present'} disabled={group.finalized} color="bg-emerald-500" onClick={()=>setStatuses(current=>({...current,[member.passengerId]:'Present'}))}/><StatusButton label="Not Present" active={statuses[member.passengerId]==='NotPresent'} disabled={group.finalized} color="bg-red-500" onClick={()=>setStatuses(current=>({...current,[member.passengerId]:'NotPresent'}))}/><StatusButton label="Not Yet Checked" active={statuses[member.passengerId]==='NotChecked'} disabled={group.finalized} color="bg-slate-500" onClick={()=>setStatuses(current=>({...current,[member.passengerId]:'NotChecked'}))}/></div></article>)}</div>{!group.finalized&&<button onClick={()=>setReview(true)} className="mt-5 w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Confirm Attendance</button>}</section>}
  <section className="overflow-hidden rounded-xl bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-6 py-5"><h2 className="text-lg font-semibold text-[#14223d]">Passenger Manifest</h2><button disabled={Boolean(manifest?.finalizedAtUtc)||summary.total===0} onClick={()=>setFinalize(true)} className="rounded-lg border border-indigo-600 px-4 py-2 text-xs font-semibold text-indigo-700 disabled:opacity-40">Complete Passenger Verification</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Passenger','Reference','Group / Relationship','Status','Check-in Time'].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{manifest?.passengers.map(person=><tr key={person.passengerId}><td className="px-5 py-4 font-semibold">{person.name}</td><td className="px-5 py-4">{person.passengerReference}</td><td className="px-5 py-4">{person.relationship}</td><td className="px-5 py-4"><StatusBadge status={person.status}/></td><td className="px-5 py-4">{person.checkedAtUtc?new Date(person.checkedAtUtc).toLocaleString():'–'}</td></tr>)}</tbody></table>{summary.total===0&&<p className="p-8 text-center text-xs text-slate-400">No passengers registered for this trip.</p>}</div></section>
  {scanner&&<QrScanner onScan={value=>void scan(value)} onClose={()=>setScanner(false)}/>} {review&&<ConfirmDialog title="Confirm Group Attendance" text={`${groupPresent} passengers marked Present · ${groupAbsent} marked Not Present.${groupUnchecked?` ${groupUnchecked} have not been checked yet.`:''}`} warning={groupUnchecked?`${groupUnchecked} passengers remain Not Yet Checked. Are you sure you want to continue?`:undefined} onBack={()=>setReview(false)} onConfirm={()=>void save()}/>} {finalize&&<ConfirmDialog title="Complete Passenger Verification" text={`${summary.present} Present · ${summary.notPresent} Not Present · ${summary.notChecked} Not Yet Checked · ${summary.total} Total`} warning={summary.notChecked?`${summary.notChecked} passengers have not been checked. Finalize anyway?`:'The manifest will be locked after finalization.'} onBack={()=>setFinalize(false)} onConfirm={()=>void finalizeManifest()}/>} 
 </section>;
}

function Metric({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${color}`}>{value}</p></div>}
function StatusBadge({status}:{status:AttendanceStatus}){const style=status==='Present'?'bg-emerald-50 text-emerald-700':status==='NotPresent'?'bg-red-50 text-red-700':'bg-slate-100 text-slate-600';const label=status==='NotPresent'?'Not Present':status==='NotChecked'?'Not Yet Checked':'Present';return <span className={`mt-2 inline-block rounded-full px-3 py-1 text-[10px] font-semibold ${style}`}>{label}</span>}
function StatusButton({label,active,disabled,color,onClick}:{label:string;active:boolean;disabled:boolean;color:string;onClick:()=>void}){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${active?`${color} border-transparent text-white`:'border-slate-200 bg-white text-slate-600'} disabled:opacity-50`}>{label}</button>}
function ConfirmDialog({title,text,warning,onBack,onConfirm}:{title:string;text:string;warning?:string;onBack:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-[1300] grid place-items-center bg-black/60 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-semibold text-[#14223d]">{title}</h2><p className="mt-3 text-sm text-slate-600">{text}</p>{warning&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{warning}</p>}<div className="mt-6 flex justify-end gap-3"><button onClick={onBack} className="rounded-lg border px-4 py-2 text-sm">Go Back</button><button onClick={onConfirm} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Confirm & Save</button></div></section></div>}

type Detector={detect:(source:HTMLVideoElement)=>Promise<Array<{rawValue:string}>>};type DetectorCtor=new(options:{formats:string[]})=>Detector;
function QrScanner({onScan,onClose}:{onScan:(value:string)=>void;onClose:()=>void}){const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const[value,setValue]=useState("");const[message,setMessage]=useState("Starting camera...");useEffect(()=>{let stopped=false;let timer=0;const start=async()=>{try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();const Ctor=(window as unknown as {BarcodeDetector?:DetectorCtor}).BarcodeDetector;if(!Ctor){setMessage('Camera opened. Automatic QR detection is not supported by this browser; paste the QR value below.');return}const detector=new Ctor({formats:['qr_code']});setMessage('Point the camera at the passenger QR code.');timer=window.setInterval(()=>{if(!video.current||stopped)return;void detector.detect(video.current).then(codes=>{if(codes[0]?.rawValue){stopped=true;onScan(codes[0].rawValue)}}).catch(()=>undefined)},400)}catch{setMessage('Camera access is unavailable. Paste the QR value below.')}};void start();return()=>{stopped=true;window.clearInterval(timer);stream.current?.getTracks().forEach(track=>track.stop())}},[onScan]);return <div className="fixed inset-0 z-[1400] grid place-items-center bg-black/80 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Scan Passenger QR</h2><p className="mt-1 text-xs text-slate-500">{message}</p></div><button onClick={onClose}><X/></button></div><video ref={video} playsInline muted className="mt-4 aspect-video w-full rounded-xl bg-black object-cover"/><div className="mt-4 flex gap-2"><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste or enter QR value" className="h-11 flex-1 rounded-lg border px-3 text-sm"/><button disabled={!value.trim()} onClick={()=>onScan(value)} className="rounded-lg bg-[#14223d] px-4 text-sm font-semibold text-white disabled:opacity-40">Validate</button></div></section></div>}
