name: wwms_app
description: "A new Flutter project for the Whale Watching Monitoring System (WWMS)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_whale.jpg
    - assets/images/bg_whale_boat.jpg
    - assets/images/slcg_logo.png
    - assets/images/fv_mirissa_king.jpg
    - assets/images/sea_princess.jpg
    - assets/images/profile_kamal.jpg
    - assets/images/qr_image.png
    - assets/images/map_image.png