import { useState } from 'react';
import { ShieldAlert,X } from 'lucide-react';
import { operationsApi } from '../../../operations/operationsApi';

export function CrewSOSButton({boatName,tripId,token,active}:{boatName:string;tripId:string;token:string;active:boolean}){
 const [open,setOpen]=useState(false),[sent,setSent]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState('');
 const send=async()=>{try{setSending(true);setError('');await operationsApi.raiseCrewSos(token,tripId);setSent(true)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to send the SOS alert.')}finally{setSending(false)}};
 return <><button type="button" onClick={()=>{setOpen(true);setSent(active);setError('')}} className="fixed bottom-5 right-5 z-50 flex h-14 items-center gap-2 rounded-full border border-red-300/50 bg-red-600 px-5 text-sm font-bold text-white shadow-[0_8px_30px_rgba(220,38,38,.45)] transition hover:bg-red-500 active:scale-[.97]" aria-label="Send emergency SOS"><ShieldAlert size={20}/>SOS</button>{open&&<div className="fixed inset-0 z-[1100] grid place-items-center bg-black/75 p-5 backdrop-blur-sm"><section role="alertdialog" aria-modal="true" aria-labelledby="crew-sos-title" className="relative w-full max-w-sm rounded-2xl border border-white/15 bg-[#171717] p-6 text-white shadow-2xl"><button onClick={()=>setOpen(false)} className="absolute right-4 top-4 text-white/60"><X size={20}/></button>{sent?<><div className="grid h-12 w-12 place-items-center rounded-full bg-red-600"><ShieldAlert/></div><h2 id="crew-sos-title" className="mt-4 text-xl font-bold">SOS sent</h2><p className="mt-2 text-sm leading-6 text-white/70">The Coast Guard operations team has been alerted with your crew identity and linked boat details. Stay calm and follow emergency procedures.</p><button onClick={()=>setOpen(false)} className="mt-6 h-11 w-full rounded-lg bg-white font-semibold text-black">Close</button></>:<><div className="grid h-12 w-12 place-items-center rounded-full bg-red-600"><ShieldAlert/></div><h2 id="crew-sos-title" className="mt-4 text-xl font-bold">Send emergency SOS?</h2><p className="mt-2 text-sm leading-6 text-white/70">Use only for an immediate safety or medical emergency aboard {boatName}. Your identity and linked boat will be included automatically.</p>{error&&<p className="mt-3 text-sm text-red-400" role="alert">{error}</p>}<button onClick={()=>void send()} disabled={sending} className="mt-6 h-11 w-full rounded-lg bg-red-600 font-bold text-white hover:bg-red-500 disabled:opacity-60">{sending?'Sending...':'Confirm SOS'}</button><button onClick={()=>setOpen(false)} className="mt-3 h-11 w-full rounded-lg border border-white/20 text-sm">Cancel</button></>}</section></div>}</>;
}
