import{Link,useNavigate,useParams}from"react-router-dom";import{useAdminRecords}from"../Admin/AdminRecordsContext";import ApprovalControls from"../Admin/components/ApprovalControls";import TripHistory from"../Admin/components/TripHistory";import TripOverview from"../OPS/components/TripOverview";
const Card=({children}:{children:React.ReactNode})=><section className="rounded-2xl bg-white p-6 shadow-sm">{children}</section>;
export function WildlifeDashboard(){const r=useAdminRecords();return <main className="mx-auto max-w-6xl px-6 py-12"><p className="text-sm text-slate-500">Wildlife Authority Portal</p><h1 className="mt-1 text-3xl font-semibold">Review boats and crew</h1><div className="mt-8 grid gap-5 md:grid-cols-3">{[["Pending boats",r.boats.filter(x=>x.approval==="Pending").length,"/wildlife/boats"],["Pending crew",r.crew.filter(x=>x.approval==="Pending").length,"/wildlife/crew"],["Active records",r.boats.length+r.crew.length,"/wildlife/trips"]].map(([l,n,p])=><Link key={l} to={p as string} className="rounded-2xl bg-white p-7 shadow-sm"><p className="text-sm text-slate-500">{l}</p><p className="mt-3 text-3xl font-bold">{n}</p><p className="mt-5 text-sm font-semibold text-indigo-700">View records →</p></Link>)}</div></main>}
export function WildlifeBoats(){const{boats,owners}=useAdminRecords();return <List title="Boats" subtitle="View and review new boat registrations"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="py-4">Boat</th><th>Owner</th><th>Registration</th><th>Status</th><th/></tr></thead><tbody>{boats.map(b=><tr key={b.id} className="border-b"><td className="py-5 font-semibold">{b.name}</td><td>{owners.find(o=>o.id===b.ownerId)?.name}</td><td>{b.registrationNumber}</td><td>{b.approval}</td><td className="text-right"><Link className="font-semibold text-indigo-700" to={`/wildlife/boats/${b.id}`}>{b.approval==="Pending"?"Review":"View"} →</Link></td></tr>)}</tbody></table></List>}
export function WildlifeCrew(){const{crew,boats}=useAdminRecords();return <List title="Boat crew" subtitle="View and review new crew registrations"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="py-4">Crew member</th><th>Role</th><th>Boat</th><th>Status</th><th/></tr></thead><tbody>{crew.map(c=><tr key={c.id} className="border-b"><td className="py-5 font-semibold">{c.name}</td><td>{c.role}</td><td>{boats.find(b=>b.id===c.boatId)?.name??"Unassigned"}</td><td>{c.approval}</td><td className="text-right"><Link className="font-semibold text-indigo-700" to={`/wildlife/crew/${c.id}`}>{c.approval==="Pending"?"Review":"View"} →</Link></td></tr>)}</tbody></table></List>}
export function WildlifeOwners(){const{owners,boats}=useAdminRecords();return <List title="Boat owners" subtitle="View owner information and registered boats"><div className="grid gap-4 md:grid-cols-2">{owners.map(o=><Card key={o.id}><h2 className="font-semibold">{o.name}</h2><p className="mt-1 text-sm text-slate-500">{o.email}</p><p className="mt-4 text-xs">{boats.filter(b=>b.ownerId===o.id).length} registered boats</p></Card>)}</div></List>}
export function WildlifeBoatDetails(){const{id}=useParams();const nav=useNavigate();const r=useAdminRecords();const b=r.boats.find(x=>x.id===Number(id));if(!b)return <main className="p-10">Boat not found.</main>;const owner=r.owners.find(o=>o.id===b.ownerId);return <Details back={()=>nav(-1)} title={b.name} subtitle={b.registrationNumber}><ApprovalControls key={b.approval} initialStatus={b.approval} initialReason={b.declineReason} onChange={(s,x)=>r.setBoatApproval(b.id,s,x)}/><Card><h2 className="font-semibold">Boat information</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><Info l="Owner" v={owner?.name??"–"}/><Info l="Capacity" v={String(b.capacity)}/><Info l="Hull number" v={b.hullNumber}/><Info l="Dimensions" v={`${b.length} × ${b.width}`}/></dl></Card><TripHistory tripIds={b.tripIds}/></Details>}
export function WildlifeCrewDetails(){const{id}=useParams();const nav=useNavigate();const r=useAdminRecords();const c=r.crew.find(x=>x.id===Number(id));if(!c)return <main className="p-10">Crew member not found.</main>;return <Details back={()=>nav(-1)} title={c.name} subtitle={c.role}><ApprovalControls key={c.approval} initialStatus={c.approval} initialReason={c.declineReason} onChange={(s,x)=>r.setCrewApproval(c.id,s,x)}/><Card><dl className="grid gap-4 text-sm sm:grid-cols-2"><Info l="NIC" v={c.nic}/><Info l="Email" v={c.email}/><Info l="Phone" v={c.phone}/><Info l="Current boat" v={r.boats.find(b=>b.id===c.boatId)?.name??"Unassigned"}/></dl></Card><TripHistory tripIds={c.tripIds}/></Details>}
export function WildlifeTrips(){return <List title="Trips" subtitle="View trip information"><div className="grid gap-4 md:grid-cols-2">{[[101,"Mirissa King","Ongoing"],[102,"Mirissa King","Completed"],[104,"Blue Horizon","Completed"]].map(([id,boat,status])=><Link key={id} to={`/wildlife/trips/${id}`} className="rounded-xl border p-5"><div className="flex justify-between"><b>Trip #{id}</b><span className="text-sm">{status}</span></div><p className="mt-2 text-sm text-slate-500">{boat}</p></Link>)}</div></List>}
export function WildlifeTripDetails(){const{id="101"}=useParams();return <TripOverview tripId={id}/>}
function List({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="mx-auto max-w-7xl px-6 py-10"><section className="rounded-2xl bg-white p-7 shadow-sm"><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p><div className="mt-7 overflow-x-auto">{children}</div></section></main>}
function Details({back,title,subtitle,children}:{back:()=>void;title:string;subtitle:string;children:React.ReactNode}){return <main className="mx-auto max-w-5xl px-6 py-10"><button onClick={back} className="text-sm font-semibold text-indigo-700">← Back</button><h1 className="mt-6 text-3xl font-semibold">{title}</h1><p className="text-sm text-slate-500">{subtitle}</p><div className="mt-6 space-y-5">{children}</div></main>};function Info({l,v}:{l:string;v:string}){return <div><dt className="text-xs uppercase text-slate-400">{l}</dt><dd className="mt-1 font-semibold">{v}</dd></div>}
