// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhaleWatching.Api.Data;

#nullable disable

namespace WhaleWatching.Api.Migrations
{
    [DbContext(typeof(WhaleWatchingDbContext))]
    [Migration("20260722050100_PassengerPersonalQrAndAttendance")]
    partial class PassengerPersonalQrAndAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrewType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCrewCertified")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NicNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePhotoContentType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NicNumber")
                        .IsUnique()
                        .HasFilter("[NicNumber] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Boat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Approval")
                        .HasColumnType("int");

                    b.Property<string>("GpsDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HullNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LengthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("LifeJacketCount")
                        .HasColumnType("int");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("MaximumSpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("WidthMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("WildlifeApproval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GpsDeviceId")
                        .IsUnique()
                        .HasFilter("[GpsDeviceId] IS NOT NULL");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.BoatDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.ToTable("BoatDocuments");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.ComplaintImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintImages");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.CrewAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CrewUserId");

                    b.HasIndex("BoatId", "CrewUserId")
                        .IsUnique();

                    b.ToTable("CrewAssignments");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.GpsTelemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<decimal?>("SpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("IX_GpsTelemetry_RecordedAtUtc");

                    b.HasIndex("DeviceId", "RecordedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_GpsTelemetry_DeviceId_RecordedAtUtc");

                    b.ToTable("GpsTelemetry", null, t =>
                        {
                            t.HasCheckConstraint("CK_GpsTelemetry_Latitude", "[Latitude] >= -90 AND [Latitude] <= 90");

                            t.HasCheckConstraint("CK_GpsTelemetry_Longitude", "[Longitude] >= -180 AND [Longitude] <= 180");
                        });
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.OwnerCrewMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CrewUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CrewUserId");

                    b.HasIndex("OwnerId", "CrewUserId")
                        .IsUnique();

                    b.ToTable("OwnerCrewMemberships");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerAttendanceAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("PassengerAttendanceAudits");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerComplaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("PassengerComplaints");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgeCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NormalizedIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PassengerType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PersonalQrToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedIdentificationNumber")
                        .IsUnique();

                    b.HasIndex("PersonalQrToken")
                        .IsUnique()
                        .HasFilter("[PersonalQrToken] IS NOT NULL");

                    b.ToTable("PassengerProfiles");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TripId");

                    b.ToTable("PassengerSessions");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "FamilyId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.SosEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("RaisedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RaisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("SosEvents");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ActualArrivalUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualDepartureUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("BoatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("int");

                    b.Property<string>("InvitationCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PassengerVerificationFinalizedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PassengerVerificationFinalizedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("ScheduledDepartureUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ShoreApproval")
                        .HasColumnType("int");

                    b.Property<string>("ShoreNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SpecialNeedsCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.HasIndex("InvitationCode")
                        .IsUnique()
                        .HasFilter("[InvitationCode] IS NOT NULL");

                    b.HasIndex("PassengerVerificationFinalizedByUserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripCrewAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CrewUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CrewUserId");

                    b.HasIndex("TripId", "CrewUserId")
                        .IsUnique();

                    b.ToTable("TripCrewAssignments");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryPassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("PrimaryPassengerId");

                    b.HasIndex("TripId", "PassengerId")
                        .IsUnique();

                    b.ToTable("TripPassengers");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassengerAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CheckedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CheckedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripPassengerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("TripPassengerId")
                        .IsUnique();

                    b.ToTable("TripPassengerAttendances");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourceTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("TransferredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DestinationTripId");

                    b.HasIndex("SourceTripId");

                    b.HasIndex("InitiatedByUserId", "ClientRequestId")
                        .IsUnique();

                    b.ToTable("TripTransfers");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripTransferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("TripTransferItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Boat", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "Owner")
                        .WithMany("OwnedBoats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.BoatDocument", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.Boat", "Boat")
                        .WithMany("Documents")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.ComplaintImage", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.PassengerComplaint", "Complaint")
                        .WithMany("Images")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.CrewAssignment", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.Boat", "Boat")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "CrewUser")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("CrewUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("CrewUser");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.OwnerCrewMembership", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "CrewUser")
                        .WithMany("CrewMemberships")
                        .HasForeignKey("CrewUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrewUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerAttendanceAudit", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.TripPassengerAttendance", "Attendance")
                        .WithMany("AuditEntries")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerComplaint", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.PassengerProfile", "Passenger")
                        .WithMany("Complaints")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerSession", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.PassengerProfile", "Passenger")
                        .WithMany("Sessions")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.SosEvent", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Trip", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.Boat", "Boat")
                        .WithMany("Trips")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "PassengerVerificationFinalizedByUser")
                        .WithMany()
                        .HasForeignKey("PassengerVerificationFinalizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Boat");

                    b.Navigation("PassengerVerificationFinalizedByUser");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripCrewAssignment", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "CrewUser")
                        .WithMany("TripAssignments")
                        .HasForeignKey("CrewUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.Trip", "Trip")
                        .WithMany("CrewAssignments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassenger", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.PassengerProfile", "Passenger")
                        .WithMany("Trips")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.PassengerProfile", "PrimaryPassenger")
                        .WithMany()
                        .HasForeignKey("PrimaryPassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.Trip", "Trip")
                        .WithMany("Passengers")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("PrimaryPassenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassengerAttendance", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WhaleWatching.Api.Domain.TripPassenger", "TripPassenger")
                        .WithOne("Attendance")
                        .HasForeignKey("WhaleWatching.Api.Domain.TripPassengerAttendance", "TripPassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedByUser");

                    b.Navigation("TripPassenger");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripTransfer", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.Trip", "DestinationTrip")
                        .WithMany()
                        .HasForeignKey("DestinationTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.ApplicationUser", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhaleWatching.Api.Domain.Trip", "SourceTrip")
                        .WithMany()
                        .HasForeignKey("SourceTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationTrip");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("SourceTrip");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripTransferItem", b =>
                {
                    b.HasOne("WhaleWatching.Api.Domain.TripTransfer", "Transfer")
                        .WithMany("Items")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.ApplicationUser", b =>
                {
                    b.Navigation("CrewAssignments");

                    b.Navigation("CrewMemberships");

                    b.Navigation("OwnedBoats");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TripAssignments");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Boat", b =>
                {
                    b.Navigation("CrewAssignments");

                    b.Navigation("Documents");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerComplaint", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.PassengerProfile", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Sessions");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.Trip", b =>
                {
                    b.Navigation("CrewAssignments");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassenger", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripPassengerAttendance", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("WhaleWatching.Api.Domain.TripTransfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
